# -*- coding: utf-8 -*-
"""day13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvOgk8qB9d-E3iTZgKSPBe5eu1jPA1jW
"""

#Filter only negative and zero in the list using list comprehension

 
# input of list
li=[]
n=int(input("Enter size of list "))
for i in range(0,n):
    e=int(input("Enter element of list "))
    li.append(e)

print("negative numbers in",li,"are: ")
  
#traversing
for i in li:
      
    # checking condition
    if i<0:
       print(i, end = " ")

def slope(x1, y1, x2, y2):
  s = (y2-y1)/(x2-x1)
  return s

print (slope(80,240,90,260))