# -*- coding: utf-8 -*-
"""day_45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eXdWY93McGq7CI1szijVRtH-Q7wam0qM
"""

Tup = ('Jan','feb','march')

tup1 = ();

Tup1 = (50,);

tup1 = ('Robert', 'Carlos','1965','Terminator 1995', 'Actor','Florida');
tup2 = (1,2,3,4,5,6,7);
print(tup1[0])
print(tup2[1:4])

x = ("Guru99", 20, "Education")    # tuple packing
(company, emp, profile) = x    # tuple unpacking
print(company)
print(emp)
print(profile)