# -*- coding: utf-8 -*-
"""day _12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_QZci8CNkNwb04fg5vqgymwg7gUBYA8
"""

#Writ a function which generates a six digit/character random_user_id

import string    
import random # define the random module  
S = 10  # number of characters in the string.  
# call random.choices() string module to find the string in Uppercase + numeric data.  
ran = ''.join(random.choices(string.ascii_uppercase + string.digits, k = S))    
print("The randomly generated string is : " + str(ran)) # print the random data

#Write a function named rgb_color_gen. It will generate rgb colors (3 values ranging from 0 to 255 each).

def random_color():
    levels = range(32,256,32)
    return tuple(random.choice(levels) for _ in range(3))

#Write a function which returns an array of seven random numbers in a range of 0-9. All the numbers must be unique.

import random

print("Generating 3 random integer number between 100 and 999 divisible by 5")
for num in range(3):
    print(random.randrange(0, 9), end=', ')

