# -*- coding: utf-8 -*-
"""day_36.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Ql-xH17V10FB7NsMC1lkwHvGL1PHnNe
"""

from array import *
print("Bytes to String: ")
x = array('b', [119, 51, 114, 101,  115, 111, 117, 114, 99, 101])
s = x.tobytes()
print(s)