# -*- coding: utf-8 -*-
"""day_39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-Au24oWxToMdrK6UOK0JsAyCMIcwy2L
"""



"""What is a Python module? How is it different from libraries?

A module is a single file (or files) containing functions, definitions, and variables designed to do certain tasks. It is a .py extension file. It can be imported at any time during a session and needs to be imported only once. To import a python module, there are two ways: import or from module_name import.

A library is a collection of reusable functionality of codes that allows us to perform a variety of tasks without having to write the code. A Python library does not have any specific context to it. It loosely refers to a collection of modules. These codes can be used by importing the library and by calling that library’s method (or attribute) with a period(.).
"""