# -*- coding: utf-8 -*-
"""day 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJwUwdlwB-M9JiJO-Fnzuga9SBCMREby
"""

print("surya");

print(dir(__builtin__));

first_name, last_name, country, age, is_married = 'Asabeneh', 'Yetayeh', 'Helsink', 250, True

print(first_name, last_name, country, age, is_married)
print('First name:', first_name)
print('Last name: ', last_name)
print('Country: ', country)
print('Age: ', age)
print('Married: ', is_married)

(###level 1
###Declare a first name variable and assign a value to it
###Declare a last name variable and assign a value to it
###Declare a full name variable and assign a value to it
###Declare a country variable and assign a value to it
###Declare a city variable and assign a value to it
###Declare an age variable and assign a value to it
###Declare a year variable and assign a value to it
###Declare a variable is_married and assign a value to it
###Declare a variable is_true and assign a value to it
###Declare a variable is_light_on and assign a value to it
###Declare multiple variable on one line)

First, Last_name, full, city, age, year, married  = ('surya', 'charan', 'surya charan', 'hyderabad', '25', '1997', 'no')

print(First ,Last_name ,full  ,city ,age ,year ,married)

print('First:', First)

print('Last name:'Last_name)

print('full:' full)

print('city:' city )

print('age:' age )

print('year:' year )

print('married:' married )

###Check the data type of all your variables using type() built-in function

num1 = 5
print(num1, 'is of type', type(num1))

###Using the len() built-in function, find the length of your first name
greeting = "suryA!"
print(len(greeting))

###Compare the length of your first name and your last name

fruit1 = input('Enter the name of the first fruit:\n')
fruit2 = input('Enter the name of the second fruit:\n')

if fruit1 < fruit2:
    print(fruit1 + " comes before " + fruit2 + " in the dictionary.")
elif fruit1 > fruit2:
    print(fruit1 + " comes after " + fruit2 + " in the dictionary.")
else:
    print(fruit1 + " and " + fruit2 + " are the same.")

###add

val1 = 4.0
val2 = 5.0

# Adding the two given numbers
sum = float(val1) + float(val2)

## sub the two given numbers
sub = float(val1) - float(val2)

## multi the two given numbers
mult = float(val1) * float(val2)

## div the two given numbers
div = float(val1) / float(val2)

## pow the two given numbers 
print(pow(3.0, 4.0));

# Displaying the addition result
print("The sum of given numbers is: ", sum)
print("The sub of given numbers is: ", sub)
print("The mult of given numbers is: ", mult)
print("The div of given numbers is: ", div)

a = 10
b = 3

print(a//b)  # 3

a = -10
b = -3

print(a//b)  # 3

a = 10
b = -3
print(a//b)  # -4

a = -10
b = 3
print(a//b)  # -4

#Calculate the area of a circle and assign the value to a variable name of area_of_circle

π = 3.14  
Radius = float (input ("Please enter the radius of the given circle: "))  
area_of_the_circle = π * Radius * Radius  
print (" The area of the given circle is: ", area_of_the_circle)

#Calculate the circumference of a circle and assign the value to a variable name of circum_of_circle
print("Enter Radius of Circle: ")
r = float(input())
pie = 3.14
c = 2 * pie * r
print("\nCircumference = ", c)



first_name, last_name, country, age, is_married = 'Asabeneh', 'Yetayeh', 'Helsink', 250, True

print(first_name, last_name, country, age, is_married)
print('First name:', first_name)
print('Last name: ', last_name)
print('Country: ', country)
print('Age: ', age)
print('Married: ', is_married)