# -*- coding: utf-8 -*-
"""day_31

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZJJeSElDD6nnP1gfEOOZkDvEPW7IxhSh
"""

def isPalindrome(s):
    return s == s[::-1]
 
 
# Driver code
s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")