# -*- coding: utf-8 -*-
"""day_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smC1tIvCoCYmqh6kgsAYxKmLshFu4DOY
"""

#Create an empty dictionary called dog

dog ={}

print(dog)


#Add name, color, breed, legs, age to the dog dictionary

dog ={
    'name' : 'lilly',
    'breed': 'indie',
    'legs': 'long',
    'age':'2'
}

print(dog)

#Create a student dictionary and add first_name, last_name, gender, age, marital status, skills, country, city and address as keys for the dictionary

student ={'first_name' : 'surya',
          'last_name' : 'mareedu',
          'gender' : 'male',
          'age' : '25',
          'marital status' : 'single',
          'skills' : 'manuel testing',
          'country' :'india',
          'city' : 'hyderabd',
          'address' : 'bharat nagar' 
    
}
   
print(student)


#Get the length of the student dictionary

print (len (student))

#Get the value of skills and check the data type, it should be a list

print(student.items())

#Modify the skills values by adding one or two skills

student["hobbies"] = "anime"

print(student)

#Get the dictionary keys as a list

keys = student.keys()
print(keys) 

#Get the dictionary values as a list

values = student.values()
print(values) 

#Change the dictionary to a list of tuples using items() method

print(student.items())

#Delete one of the items in the dictionary

student.pop('first_name') 

#Delete one of the dictionaries

print(student)

del student