# -*- coding: utf-8 -*-
"""day_15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Qtu32ViN1eUYso2PJf_6MxJ7hvi97m6
"""

print 'hello world'

print('hello world')

print(age)

age = 25
print(age)

numbers = [1, 2, 3, 4, 5]
numbers[5]

import maths

import math

import math
math.PI

math.pi

user = {'name':'Asab', 'age':250, 'country':'Finland'}

user['name']
user['country']

4 + int('3')

from math import pow
pow(2,3)

1/0