# -*- coding: utf-8 -*-
"""Day 5 - Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dS_xKOp1ql-dG75hps6nNWjVn5qKVK2K
"""

#Declare an empty list

empty_list = list() # this is an empty list, no item in the list
print(len(empty_list))

#Declare a list with more than 5 items

vegetables = ['Tomato', 'Potato', 'Cabbage','Onion', 'Carrot'] 
print('Vegetables:', vegetables)

#Find the length of your list
print('Number of vegetables:', len(vegetables))

#Get the first item, the middle item and the last item of the list
f_s =vegetables[0]
print(f_s)
m_s =vegetables[2]
print(m_s)
l_s =vegetables[4]
print(l_s)


#Declare a list called mixed_data_types, put your(name, age, height, marital status, address)

name = 'surya'
age = '26'
height = '165'
maritalstatus = 'single'
address = 'hyd'

mixed_data_types =[name, age, height, maritalstatus, address]

print(mixed_data_types)

#Declare a list variable named it_companies and assign initial values Facebook, Google, Microsoft, Apple, IBM, Oracle and Amazon.

it_companies = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
print(it_companies)

#Print the list using print()

#Print the number of companies in the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
print(elem_list)

#Print the first, middle and last company

f_s =elem_list[0]
print(f_s)
m_s =elem_list[3]
print(m_s)
l_s =elem_list[6]
print(l_s)

#Print the list after modifying one of the companies

#Add an IT company to it_companies

elem_list.insert(2, 'verizon') 
print(elem_list) 

#Insert an IT company in the middle of the companies list

#Change one of the it_companies names to uppercase (IBM excluded!)

#Join the it_companies with a string '#;  '

#Check if a certain company exists in the it_companies list.

#Sort the list using sort() method

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
print(elem_list.sort())

#Reverse the list in descending order using reverse() method

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
print(elem_list[: : -1])

#Slice out the first 3 companies from the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
print(elem_list[:3])

#Slice out the last 3 companies from the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
print(elem_list[3:])

#Slice out the middle IT company or companies from the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
print(elem_list[3:4])

#Remove the first IT company from the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
del elem_list[0]
print(elem_list)

#Remove the middle IT company or companies from the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
del elem_list[3]
print(elem_list)


#Remove the last IT company from the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
elem_list.pop()
print(elem_list)

#Remove all IT companies from the list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
elem_list.clear()
print(elem_list)


#Destroy the IT companies list

elem_list = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' , 'Amazon']
del elem_list

#The following is a list of 10 students ages:
#ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
#Sort the list and find the min and max age
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
ages.sort()
print(ages) 
#Add the min age and the max age again to the list

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]

print(min.ages())
print(max.ages())

#Find the median age (one middle item or two middle items divided by two)
#Find the average age (sum of all items divided by their number )
#Find the range of the ages (max minus min)
#Compare the value of (min - average) and (max - average), use abs() method