# -*- coding: utf-8 -*-
"""Day_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAZXZFo0fzp8yfdm6DMoZfFozymzavHh
"""

#Exercises: Level 1
#Find the length of the set it_companies


it_companies ={'google','facebok','meta','mckensky'}

#len(it_companies)
#print(it_companies)

#Add 'Twitter' to it_companies

it_companies.add('Twitter')

print(it_companies)

#Insert multiple IT companies at once to the set it_companies

prod = {'itc','tata','wipro'}

it_companies.update(prod)

print(it_companies)

#Remove one of the companies from the set it_companies

it_companies.remove('Twitter')
print(it_companies)

#What is the difference between remove and discard

#The discard() method removes the specified item from the set.
# This method is different from the remove() method, because the remove() method will raise an error if the specified item does not exist, and the discard() method will not.


#Join A and B

a = {'item1', 'item2', 'item3', 'item4'}
b = {'item5', 'item6', 'item7', 'item8'}
c = a.union(b)
print(c)

#Find A intersection B

a.intersection(b)


#Is A subset of B

b.issubset(a) 

#Are A and B disjoint sets

a.isdisjoint(b)


#Join A with B and B with A

a.isdisjoint(b)
b.isdisjoint(a) 


#What is the symmetric difference between A and B

a.symmetric_difference(b)

#Delete the sets completely

del a

#Convert the ages to a set and compare the length of the list and the set, which one is bigger?

a = {'16', '15', '14','17'}

print(len(a))


#Explain the difference between the following data types: string, list, tuple and set


#Tuples in Python
#A tuple is a sequence of immutable Python objects. Tuples are just like lists with the exception that tuples cannot be changed once declared. Tuples are usually faster than lists.

#tup = (1, "a", "string", 1+2) 

#print tup 

#print tup[1] 

#Strings in Python
#A string is a sequence of characters. It can be declared in python by using double quotes. Strings are immutable, i.e., they cannot be changed.

# Assigning string to a variable 

#a = "This is a string"

#print a 

#Lists in Python
#Lists are one of the most powerful tools in python. They are just like the arrays declared in other languages. But the most powerful thing is that list need not be always homogenous. A single list can contain strings, integers, as well as objects. Lists can also be used for implementing stacks and queues. Lists are mutable, i.e., they can be altered once declared.

# Declaring a list 

#L = [1, "a" , "string" , 1+2] 

#print L 

#L.append(6) 

#print L 

#L.pop() 

#print L 

#print L[1] 

#I am a teacher and I love to inspire and teach people. How many unique words have been used in the sentence? Use the split methods and set to get the unique words.

#txt = " I am a teacher and I love to inspire and teach people"

#x = txt.split()

#unique = set(x)

#print(unique)