# -*- coding: utf-8 -*-
"""day_28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zbypK6lEreDicr7uBA-yAeAru-rScpvI
"""



"""Request Methods
  
The GET, POST, PUT and DELETE are the HTTP request methods which we are going to implement an API or a CRUD operation application.

GET: GET method is used to retrieve and get information from the given server using a given URI. Requests using GET should only retrieve data and should have no other effect on the data.

POST: POST request is used to create data and send data to the server, for example, creating a new post, file upload, etc. using HTML forms.

PUT: Replaces all current representations of the target resource with the uploaded content and we use it modify or update data.

DELETE: Removes data

The message body

An HTTP message may have a body of data sent after the header lines. In a response, this is where the requested resource is returned to the client (the most common use of the message body), or perhaps explanatory text if there's an error. In a request, this is where user-entered data or uploaded files are sent to the server.

If an HTTP message includes a body, there are usually header lines in the message that describe the body. In particular,

The Content-Type: header gives the MIME-type of the data in the body(text/html, application/json, text/plain, text/css, image/gif). The Content-Length: header gives the number of bytes in the body.

API stands for Application Programming Interface. It is a set of rules and protocols for building software and applications. These rules define how software components should interact with each other and with external services.

HTTP (Hypertext Transfer Protocol) is a protocol used for transmitting data over the internet. It is the foundation of the World Wide Web and is used for sending and receiving data between a web browser and a web server. HTTP defines a set of methods, such as GET, POST, and PUT, which indicate the type of action to be performed on a resource, and a set of response codes, such as 200 OK and 404 Not Found, which indicate the status of the request.

APIs often use HTTP as the underlying protocol for sending and receiving data. When a client (such as a mobile app or website) makes a request to an API, it sends an HTTP request, and the API sends back an HTTP response. The request typically includes information such as the endpoint being requested, the method being used (GET, POST, etc.), and any data being sent to the API. The response includes information such as the status code indicating the outcome of the request, and any data returned by the API.
"""