# -*- coding: utf-8 -*-
"""day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nGgMaq6D9lJgoM5z-SbWXgwg3IrUMNm
"""

#Declare your age as integer variable

age = 25
print (age)
print(type(age))

#Declare your height as a float variable
height = 5.5
print(height)
print(type(height))

#Declare a variable that store a complex number

print('Complex number: ', 1 + 1j)

#Write a script that prompts the user to enter base and height of the triangle and calculate an area of this triangle (area = 0.5 x b x h).

length = int(input())
width = int(input())
area_of_rectangle = length * width
print('Area of rectangle:', area_of_rectangle)

#Write a script that prompts the user to enter side a, side b, and side c of the triangle. Calculate the perimeter of the triangle (perimeter = a + b + c).
a=int(input())
b=int(input())
c=int(input())
perimeter = a+b+c
print('perimeter of the triangle : ',perimeter)

#Get length and width of a rectangle using prompt. Calculate its area (area = length x width) and perimeter (perimeter = 2 x (length + width))
l =int(input())
w=int(input())
a=l*w
p=2*(l+w)
print(a)
print(p)

#Get radius of a circle using prompt. Calculate the area (area = pi x r x r) and circumference (c = 2 x pi x r) where pi = 3.14.

pi =3.14
r=int(input())
a=pi*r*r
c=2*pi*r

print(a)
print(c)

#Calculate the slope, x-intercept and y-intercept of y = 2x -2
x = int(input())
y = int(input())

y=2*x-2

#Find the length of 'python' and 'dragon' and make a falsy comparison statement.

a=len('python')
b=len('dragon')

print(a)
print(b)

#Even numbers are divisible by 2 and the remainder is zero. How do you check if a number is even or not using python?
k=int(input())
if (k % 2) == 0:
  print ('is even')
else:
  print ('is odd')

#Check if the floor division of 7 by 3 is equal to the int converted value of 2.7.
print(7/3)

#Check if type of '10' is equal to type of 10

k =int(input())

if k == 10:
  print(True)
else:
  print(False)

#Check if int('9.8') is equal to 10

K= int(input())
if k == 10:
  print(True)
else:
  print(False)

#Writ a script that prompts the user to enter hours and rate per hour. Calculate pay of the person?
hours = int(input())
rate =int(input())

person =hours*rate
print('pay of the person :' ,person)

#Write a script that prompts the user to enter number of years. Calculate the number of seconds a person can live. Assume a person can live hundred years

y = float(input("How many years? "))

d = y * 365
h = d * 24
m = h * 60
s = m * 60

print(y, "years is:")
print(d, "days")
print(h, "hours")
print(m, "minutes")
print(s, "seconds")