# -*- coding: utf-8 -*-
"""Day_34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eS0oY-V5KWACRyEu8nzMZPCjkK1eYTfc
"""

from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
print("Length in bytes of one array item: "+str(array_num.itemsize))