# -*- coding: utf-8 -*-
"""day_32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aLVHDBKbNidC9G20B9uJNa_-KDDLA8Pj
"""

n = int(input("please give a number : "))
print("before reverse your numeber is : %d" %n)
reverse = 0
while n!=0:
    reverse = reverse*10 + n%10       
    n = (n//10)
print("After reverse : %d" %reverse)