# -*- coding: utf-8 -*-
"""day_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ng-R_dc5yYHD58VrGKpJ-J_xjw4ZycEM
"""

#Get user input using input(“Enter your age: ”). If user is 18 or older,
# give feedback: You are old enough to drive. If below 18 give feedback 
#to wait for the missing amount of years. Output:



# getting input 
age = int(input("Enter your age: "))  
# if-else statement 
if (age > 18): 
	print("You are old enough to learn to drive.") 
else: 
	print("You are not old enough to learn to drive." )

#Compare the values of my_age and your_age using if … else. Who is 
#older (me or you)? Use input(“Enter your age: ”) to get the age as input. 
#You can use a nested condition to print 'year' for 1 year difference in age,
# 'years' for bigger differences, and a custom text if my_age = your_age. Output:

your_age = int(input( 'Enter your age: ' ));
my_age = int(input('Enter your age: '));

if (your_age > my_age ):
  print('your_age is greater number')
elif (my_age >your_age ):
  print('your_age is greater number')
else:
  print('both are equal')


  


print(your_age)
print(my_age)

#Write a code which gives grade to students according to theirs scores:

#80-100, A
#70-89, B
#60-69, C
#50-59, D
#0-49, F

i = int(input('enter the number :'))
if i >90 and i< 100:
  print('enter grade A')
if i >70 and i< 89:
  print('enter grade B')
if i >60 and i< 69:
  print('enter grade C')
if i >50 and i< 59:
  print('enter grade D')
if i >0 and i< 49:
  print('enter grade E')

#Check if the season is Autumn, Winter, Spring or Summer. If the user input is: September, October or November, the season is Autumn. 
#December, January or February, the season is Winter. 
#March, April or May, the season is Spring June, July or August, the season is Summer

month = input("Input the month: ")


if month in ('January', 'February', 'December'):
	season = 'winter'
elif month in ('August', 'July', 'June'):
	season = 'Summer'
elif month in ('November', 'October', 'September'):
	season = 'Autumn'
else:
	season = 'Spring'

print("Season is",season)

