# -*- coding: utf-8 -*-
"""day_43.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzEUB9daa7jDQ0ge5x38b-6OzqOpduk4
"""



print("Hello, World!")