# -*- coding: utf-8 -*-
"""day_17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nW3fKB4TR9foFO4ovHmN6SDX-82KhcOy
"""

**Python uses try and except to handle errors gracefully. A graceful exit (or graceful handling) of errors is a simple programming idiom - a program detects a serious error condition and "exits gracefully", in a controlled manner as a result.**

try:
    name = input('Enter your name:')
    year_born = input('Year you were born:')
    age = 2023 - year_born
    print(f'You are {name}. And your age is {age}.')
except TypeError:
    print('Type error occured')
except ValueError:
    print('Value error occured')
except ZeroDivisionError:
    print('zero division error occured')

try:
    name = input('Enter your name:')
    year_born = input('Year you born:')
    age = 2023 - int(year_born)
    print('You are {name}. And your age is {age}.')
except TypeError:
    print('Type error occur')
except ValueError:
    print('Value error occur')
except ZeroDivisionError:
    print('zero division error occur')
else:
    print('I usually run with the try block')
finally:
    print('I alway run.')

def sum_of_five_nums(a, b, c, d, e):
    return a + b + c + d + e

lst = [1, 2, 3, 4, 5]
print(sum_of_five_nums(lst))

def sum_of_five_nums(a, b, c, d, e):
    return a + b + c + d + e

lst = [1, 2, 3, 4, 5]
print(sum_of_five_nums(*lst))

nordic_countries = ['Finland', 'Sweden', 'Norway','Denmark','Iceland', 'Estonia','Russia']
fin, sw, nor,den,Ice, *rest = nordic_countries
print(fin, sw, nor,den,Ice, rest)


## Unpack the first five countries and store them in a variable nordic_countries, store Estonia and Russia in es, and ru respectively.

##zip 

fruits = ['banana', 'orange', 'mango', 'lemon', 'lime']                    
vegetables = ['Tomato', 'Potato', 'Cabbage','Onion', 'Carrot']
fruits_and_veges = []
for f, v in zip(fruits, vegetables):
    fruits_and_veges.append({'fruit':f, 'veg':v})

print(fruits_and_veges)

##enum

for index, i in enumerate(country):
    print('hi')
    if i == 'Finland':
        print('The country {i} has been found at index {index}')